### ISSUE TITLE
ER_NOT_SUPPORTED_AUTH_MODE

### ISSUE THREAD

**Issue by felixcaldeira** [fdl-stuff/nashi#1]
```
TypeError: Cannot set property 'type' of undefined
    at C:\users\felix\desktop\programming\nashi\server.js:86:19
    at Layer.handle_error (C:\users\felix\desktop\programming\nashi\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\users\felix\desktop\programming\nashi\node_modules\express\lib\router\index.js:315:13)
    at C:\users\felix\desktop\programming\nashi\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\users\felix\desktop\programming\nashi\node_modules\express\lib\router\index.js:335:12)
    at next (C:\users\felix\desktop\programming\nashi\node_modules\express\lib\router\index.js:275:10)
    at Layer.handle_error (C:\users\felix\desktop\programming\nashi\node_modules\express\lib\router\layer.js:67:12)
    at trim_prefix (C:\users\felix\desktop\programming\nashi\node_modules\express\lib\router\index.js:315:13)
    at C:\users\felix\desktop\programming\nashi\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\users\felix\desktop\programming\nashi\node_modules\express\lib\router\index.js:335:12)


Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:518:11)
    at ServerResponse.header (C:\users\felix\desktop\programming\nashi\node_modules\express\lib\response.js:771:10)
    at ServerResponse.send (C:\users\felix\desktop\programming\nashi\node_modules\express\lib\response.js:170:12)
    at done (C:\users\felix\desktop\programming\nashi\node_modules\express\lib\response.js:1008:10)
    at tryHandleCache (C:\users\felix\desktop\programming\nashi\node_modules\ejs\lib\ejs.js:278:5)
    at View.exports.renderFile [as engine] (C:\users\felix\desktop\programming\nashi\node_modules\ejs\lib\ejs.js:489:10)
    at View.render (C:\users\felix\desktop\programming\nashi\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\users\felix\desktop\programming\nashi\node_modules\express\lib\application.js:640:10)
    at Function.render (C:\users\felix\desktop\programming\nashi\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\users\felix\desktop\programming\nashi\node_modules\express\lib\response.js:1012:7)
```

**Comment by felixcaldeira** [comment]
im dumb i knew this error already fix is querying 

ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password'

flush privileges;

or install with old password yes bye

**Comment by felixcaldeira** [comment]
https://gist.github.com/pishangujeniya/0f839d11a7e692dadc49821c274a2394
